import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/Header";
import BreadcrumbsContainer from "./breadcrumbs";
import { Toaster } from "react-hot-toast";

//const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const geistSans = GeistSans;

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    "min-h-screen bg-background font-sans antialiased",
                    geistSans.variable,
                    GeistMono.variable
                )}
            >
                <Header />
                <BreadcrumbsContainer />
                {children}
                <Toaster />
            </body>
        </html>
    );
}
